DATABASE_URL = "postgresql://localhost:5432/myapp"
REDIS_URL = "redis://localhost:6379"
SECRET_KEY = "change-me-in-production"
STRIPE_API_KEY = "sk_test_placeholder"
WEBHOOK_SECRET = "whsec_placeholder"
